# <font color="DarkCyan">CSE111-Midterm-Fall-2021</font>

# <font color='darkpink'> Question-1</font>
***Design the required class(es) to get the output shown from the driver code.\
Your code should work for any number of arguments in addStudent method of the SDS class.***


**Output:**\
School of Data and Sciences 2021! Only CSE and MNS department students can be added.
  
\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\
Number of CSE students: 0\
Number of MNS students: 0\
CSE Students {}\
MNS Students {}\
1.================================\
Name: Maliha\
ID: 21101001\
Department: MNS\
Courses: []\
CGPA: 0\
2.================================\
Number of CSE students: 0\
Number of MNS students: 1\
CSE Students {}\
MNS Students {21101001: ['Maliha', 0, []]}\
3.================================\
Name: Subha\
ID: 21301001\
Department: CSE\
Courses: ['ENG091', 'MAT092']\
CGPA: 3.48\
4.================================\
Number of CSE students: 1\
Number of MNS students: 1\
CSE Students {21301001: ['Subha', 3.48, ['ENG091', 'MAT092']]}\
MNS Students {21101001: ['Maliha', 0, []]}\
5.================================\
6.================================\
Name: Samiul\
ID: 21305001\
Department: MNS\
Courses: ['ENG091', 'MAT092', 'PHY111']\
CGPA: 3.01\
7.================================\
Name: Mohsina\
ID: 21305023\
Department: MNS\
Courses: []\
CGPA: 0\
8.================================\
9.================================\
Number of CSE students: 1\
Number of MNS students: 3\
CSE Students {21301001: ['Subha', 3.48, ['ENG091', 'MAT092']]}\
MNS Students {21101001: ['Maliha', 0, []], 21305001: ['Samiul', 3.01, ['ENG091', 'MAT092', 'PHY111']], 21305023: ['Mohsina', 0, []]}\
10.================================\
BBS department student cannot be added to SDS\
11.================================\
Number of CSE students: 1\
Number of MNS students: 3\
CSE Students {21301001: ['Subha', 3.48, ['ENG091', 'MAT092']]}\
MNS Students {21101001: ['Maliha', 0, []], 21305001: ['Samiul', 3.01, ['ENG091', 'MAT092', 'PHY111']], 21305023: ['Mohsina', 0, []]}

In [ ]:
# Write you code here




#======================================================================
#Do not change the codes below
sds21 = SDS("2021")
print("*********************************************")
sds21.print_info()
print("1.================================")
s1 = Student("Maliha",21101001)
s1.print_info()
print("2.================================")
sds21.addStudent(s1)
sds21.print_info()
print("3.================================")
s2 = Student("Subha",21301001,"CSE", ["ENG091","MAT092"],3.48)
s2.print_info()
print("4.================================")
sds21.addStudent(s2)
sds21.print_info()
print("5.================================")
s3 = Student("Samiul",21305001,"MNS", ["ENG091","MAT092","PHY111"],3.01)
s4 = Student("Mohsina",21305023)
print("6.================================")
s3.print_info()
print("7.================================")
s4.print_info()
print("8.================================")
sds21.addStudent(s3,s4)
print("9.================================")
sds21.print_info()
print("10.================================")
s5 = Student("Nayla", 16101288, "BBS")
sds21.addStudent(s5)
print("11.================================")
sds21.print_info()

# <font color='darkpink'> Question-2</font>
***Design the required class(es) so that the following expected output is generated. Do not change any given code.\
Your code should work for any number of arguments in <font color='blue'>\_\_init_\_</font> and <font color='blue'>setToppings</font> method of pizza class. For simplicity,\
you can consider there will be only 3 categories of pizzas and they are: Chicken, Beef, Cheese.***


**Output:**\
Domino’s. The Pizza Delivery Experts.\
1.======================================\
2.======================================\
A pizza without toppings cannot be created.\
3.======================================\
Toppings added to Beef Kala Bhuna pizza.\
4.======================================\
5.======================================\
Total number of pizzas: 5\
Chicken Pizza:2\
Name:Spicy Chicken, Toppings: ['Spicy Chicken', 'Onion', 'Capsicum']\
Name:Chicken Dominator, Toppings: ['Barbecue Chicken,Spicy Chicken,Grilled Chicken']

Beef Pizza:2\
Name:Beef Kala Bhuna, Toppings: ['Curried Beef', 'Capsicum', 'Paprika', 'Onion']\
Name:Beefzza, Toppings: ['Minced Beef', 'Beef Pepperoni', 'Onion', 'Jalapeno']

Cheese Pizza: 1\
Name:Margherita, Toppings: ['Mozzarella Cheese']\
6.======================================

In [ ]:
# Write you code here

class Dominos:
    def __init__(self,dom_name):
        print('Domino’s. The Pizza Delivery Experts.')
        self.dic={}
    def addPizza(self,*info):
        for obj in info:
            self.dic[obj.name]=obj.li
           
    def showMenu(self):
        chicken=0
        beef=0
        cheese=0
        for key,val in self.dic.items():
            if 'Chicken' in key:
                chicken+=1
                
        
class Pizza:
    def __init__(self,*args):
        self.li=[]
        self.name=args[0]
        if len(args)>1:
            self.li=args[1:]
    def setToppings(self,*args):
        for i in args:
            self.li.append(i)
        
            
        


#======================================================================
#Do not change the codes below
dom = Dominos("Domino's Pizza")
print("1.=================================")
p1 = Pizza("Spicy Chicken","Spicy Chicken","Onion","Capsicum")
dom.addPizza(p1)
p2 = Pizza("Margherita","Mozzarella Cheese")
print("2.=================================")
p3 = Pizza("Beef Kala Bhuna")
print("3.=================================")
p3.setToppings("Curried Beef","Capsicum","Paprika","Onion")
print("4.=================================")
dom.addPizza(p2,p3)
p4 = Pizza("Chicken Dominator","Barbecue Chicken,Spicy Chicken,Grilled Chicken")
p5 = Pizza("Beefzza","Minced Beef","Beef Pepperoni","Onion","Jalapeno")
dom.addPizza(p4,p5)
print("5.=================================")
dom.showMenu()
print("6.=================================")

In [ ]:
 if 'Chicken'in obj.name:
                if 'Chicken'not in self.dic.keys():
                    self.dic['Chicken Pizza']=[obj.name,obj.li]
                else:
                    self.dic['Chicken Pizza'].append([obj.name,obj.li])
            if 'Beef'in self.name:
                if 'Beef'not in self.dic.keys():
                    self.dic['Beef Pizza']=[args[1:]]
                else:
                    self.dic['Beef Pizza'].append(args[1:])
            if 'Cheese'in self.name:
                if 'Chicken'not in self.dic.keys():
                    self.dic['Cheese Pizza']=[args[1:]]
                else:
                    self.dic['Cheese Pizza'].append(args[1:])

In [2]:
a=[1,2,3,4,5]
print(a[1:])

[2, 3, 4, 5]

# <font color='darkpink'> Question-3</font>
Suppose you are developing an apartment rental application where apartment owners will post advertisements of their\
apartments which they want to offer for rent. Now whenever an apartment owner posts an advertisement, you have to assign a\
unique ID to that advertisement using the information provided in it and store the information in a dictionary. So you will be\
given a list of advertisements of apartments as input and your task will be to store the information of that advertisement in a\
dictionary by generating a unique ID for those advertisements. Unique ID will generated using the following convention:\
  **ID = “last 2 digits of postal code” + “Road number” + “House Number”**\
Your sample input will be in following format:\
 Area PostalCode HouseNo RoadNo SizeofApartment Rent\
See the sample output to understand how your resultant dictionary will look.


**Sample Input:**\
5 <font color="blue">[This is the number of advertisements that will be given as input.]</font>\
Dhanmondi 1209 9A 128 1700sqft 45000\
Mirpur 1216 6B 10 1350sqft 23000\
Dhanmondi 1209 4A 43 1616sqft 40000\
Gulshan 1212 7C 102 2000sqft 60000\
Mirpur 1216 5A 103 1800sqft 33000\

**Sample Output:** (No need to follow this output format, just print the resultant dictionary.)\
{\
 Dhanmondi:\
       {\
   “099A128”: [“1700sqft”,45000]',\
  “094A43”: [“1616sqft”,40000]\
 }\
 Mirpur:\
       {\
   “166B10”: [“1350sqft”,23000],\
  “165A103”: [“1800sqft”,33000]\
 }\
 Gulshan:\
       {\
   “127C102”:[“2000sqft”,60000]\
 }\
}

In [ ]:
#todo

# <font color='darkpink'> Question-4</font>
***Design the required class(es) so that the following expected output is\
generated. Please use the following logic to calculateCost method.\
For each Forward the cost is 500\
For each Defender the cost is 450***


**Output:**\
1.============================================\
No players assigned yet\
2.============================================\
No cost yet as there is no players\
3.============================================\
Team Name: Argentina\
World Cup Win: 2\
Language: Spanish\
4.============================================\
5.============================================\
Total Cost: 1450\
6.============================================\
Team Name: Argentina\
World Cup Win: 2\
Language: Spanish\
Forwards:\
Messi\
Maria\
Defenders:\
Marcos\
7.============================================\
[('Messi', 'Forward'), ('Maria', 'Forward'), ('Marcos', 'Defender')]\
8.###############################################\
9.============================================\
No players assigned yet\
10.============================================\
No cost yet as there is no players\
11.============================================\
Team Name: Brazil\
World Cup Win: 5\
Language: Portuguese\
12.============================================\
13.============================================\
Total Cost: 950\
14.============================================\
Team Name: Brazil\
World Cup Win: 5\
Language: Portuguese\
Forwards:\
Neymar\
Defenders:\
Silva\
15.============================================\
[('Silva', 'Defender'), ('Neymar', 'Forward')]

In [ ]:
# Write you code here




#=======================================================
# Do not change the following lines of code.
argentina = Team("Argentina", 2)
print("1.============================================")
print(argentina.player_list)
print("2.============================================")
argentina.calculateCost()
print("3.============================================")
argentina.printDetail()
print("4.============================================")
messi = Player("Messi")
maria = Player("Maria")
marcos = Player("Marcos", "Defender")
argentina.addPlayer(messi)
argentina.addPlayer(maria)
argentina.addPlayer(marcos)
print("5.============================================")
argentina.calculateCost()
print("6.============================================")
argentina.printDetail()
print("7.============================================")
print(argentina.player_list)
print("8.###############################################")
brazil = Team("Brazil", 5, "Portuguese")
print("9.============================================")
print(brazil.player_list)
print("10.============================================")
brazil.calculateCost()
print("11.============================================")
brazil.printDetail()
print("12.============================================")
silva = Player("Silva", "Defender")
neymar = Player("Neymar")
brazil.addPlayer(silva)
brazil.addPlayer(neymar)
print("13.============================================")
brazil.calculateCost()
print("14.============================================")
brazil.printDetail()
print("15.============================================")
print(brazil.player_list)

# <font color='darkpink'> Question-5</font>
***Suppose you are working as a Software Engineer in an online streaming\
service. You are given the following tuple where all the information of a\
movie is given as <font color="blue">[Actor’sCountry MovieName Actor’sName].</font>***

my_tuple = ("UK NoTimeToDie DanielCraige", "USA MissionImpossible\
TomCruise", "USA TopGun TomCruise", "USA Troy BradPitt", "UK Skyfall\
DanielCraige", "UK TheTheoryOfEveryting EddieRedmayne", "UK FantasticBeast\
EddieRedmayne", "USA Seven BradPitt")

Your task is to write a python program that will create an ID for all the\
movies and store it in a dictionary and then print the dictionary. Your\
dictionary should be as expected output and while generating the ID ensure\
the following criteria are met. Finally print the dictionary.

For the first digit, if country is UK = 2 and USA = 1\
Then, if actor is DanielCraige = 04, TomCruise = 03, BradPitt = 02 and\
EddieRedmayne = 01\
Use the tuple’s index number as the last digit.

**Expected Output:**\
{'USA': [('MissionImpossible', 1031), ('TopGun', 1032), ('Troy', 1023), \
('Seven', 1027)], 'UK': [('NoTimeToDie', 2040), ('Skyfall', 2044), \
('TheTheoryOfEveryting', 2015), ('FantasticBeast', 2016)]}

**Explanation:** ID of MissionImpossible is 1031. This actor is from the USA so\
the first digit is 1, as the actor is TomCruise so 2nd and 3rd digits are\
03 and last digit 1 represents that item is situated at index 1 in the\
my_tuple. You must store the movie name and movie ID in a tuple and save\
that tuple in a list as the value of the dictionary. You Must Store The ID\
as an Integer.

In [ ]:
#todo

# <font color='darkpink'> Question-6</font>
Managing deadlines in the online semester has become a difficult job for\
your best friend.\
He is worried that if he cannot keep track of the deadlines then he might\
miss a lot of\
submissions and hence cannot do well in the semester. So, he asked your\
help to create a\
**<font color='blue'>basic bot for him where he will be able to:\
     - add new deadlines\
     - view all the deadlines sorted by dates.**</font>

***Now, write a Python program to design the bot for your friend. The bot will\
run until "STOP" is found.***

**Sample Input #1:**\
cse111 quiz2 22/11/2021\
cse221 mid 29/11/2021\
cse320 quiz3 25/11/2021\
cse221 quiz2 22/11/2021\
STOP

**Sample Output #1:**\
22/11/2021\
CSE111 || QUIZ2\
CSE221 || QUIZ2\
\===============\
25/11/2021\
CSE320 || QUIZ3\
\===============\
29/11/2021\
CSE221 || MID

**Sample Input #2:**\
cse111 mid 19/11/2021\
mat110 mid 19/11/2021\
cse111 quiz3 17/12/2021\
cse320 quiz2 27/11/2021\
cse230 quiz2 17/12/2021\
STOP

**Sample Output #2:**\
19/11/2021\
CSE111 || MID   \
MAT110 || MID\
\===============\
27/11/2021\
CSE320 || QUIZ2\
\===============\
17/12/2021\
CSE111 || QUIZ3\
CSE230 || QUIZ2

In [ ]:
#todo

# <font color='darkpink'> Question-7</font>

***Design the required class(es) so that the following expected output is\
generated. Do not change any given code.***


**Output:**\
1.===========================\
Sam has taken the Bus.\
2.===========================\
Calculating fare for Sam\
3.===========================\
Destination cannot be empty!\
4.===========================\
Destination of Bran is updated to Chittagong\
5.===========================\
John has taken the Bus.\
This is an Inter-City Bus. Bran cannot take the Bus.\
6.===========================\
Calculating fare for John\
7.===========================\
Mark has taken the Bus.\
This is an Inter-City Bus. Jack cannot take the Bus.\
8.===========================\
Calculating fare for Mark\
\===========================\
Details of Dhaka-123 Bus of SR Travels:\
Total Passengers: 3\
Passenger name : Sam, Destination: Dhaka, Ticket Price: 40\
Passenger name : John, Destination: Dhaka, Ticket Price: 40\
Passenger name : Mark, Destination: Dhaka, Ticket Price: 40\
9.===========================\
This is an Inter-City Car. Sam cannot take the Car.\
Bran has taken the Car.\
10.===========================\
Calculating fare for Bran\
11.===========================\
Details of Chittagong-798 Car of Uber:\
Total Passengers: 1\
Passenger name : Bran, Destination: Chittagong, Ticket Price: 250\
Jack has taken the Car.\
12.===========================\
Calculating fare for Jack\
13.===========================\
Details of Khulna-997 Car of Obhai:\
Total Passengers: 1\
Passenger name : Jack, Destination: Khulna, Ticket Price: 90

In [13]:
# Write you code here
class Vehicle:
    def __init__(self,place,vehi,orga,dic):
        self.place=place
        self.vehi=vehi
        self.orga=orga
        self.dic=dic
        self.count=0
        self.info=[]
    def addPassenger(self,*info):
        for obj in info:
            if obj.city in self.place:
                self.name=obj.name
                print(f'{obj.name} has taken the {self.vehi}.')
                self.count+=1
                self.info.append(obj.name)
                self.info.append(obj.city)
            else:
                print(f"This is an Inter-City {self.vehi}. {obj.name} cannot take the {self.vehi}.")
    def status(self):
        fee=0
        for key,val in self.dic.items():
            if key==self.orga:
                fee=val
        if fee==0:
            fee=90
        print(f"Details of {self.place} {self.vehi} of {self.orga}:\nTotal Passengers: {self.count}")
        for i in range(0,len(self.info),2):
            print(f"Passenger name : {self.info[i]}, Destination: {self.info[i+1]}, Ticket Price: {fee}")
        
class Passenger:
    def __init__(self,name,city='None'):
        self.name=name
        if city=='None':
            print("Destination cannot be empty!")
        else:
            self.city=city
    def setDestination(self,city):
        self.city=city
        print(f"Destination of {self.name} is updated to {self.city}")
    def calculateFare(self,obj):
        print(f"Calculating fare for {obj.name}")
        self.calc=0
        for key,val in obj.dic.items():
            if key==obj.orga:
                self.calc+=val
        
        
        


#=================================================
#Do not change the codes below

fareChart = {'SR Travels': 40, 'ENA': 50, 'Pathao': 200, 'Uber': 
250, 'Hanif Paribahan': 45, 'Others': 90 }
v1 = Vehicle("Dhaka-123", "Bus", 'SR Travels', fareChart)
p1 = Passenger("Sam", "Dhaka")
print("1.===========================")
v1.addPassenger(p1)
print("2.===========================")
p1.calculateFare(v1)
print("3.===========================")
p2 = Passenger("John", "Dhaka")
p3 = Passenger("Bran")
print("4.===========================")
p3.setDestination("Chittagong")
print("5.===========================")
v1.addPassenger(p2, p3)
print("6.===========================")
p2.calculateFare(v1)
print("7.===========================")
p4 = Passenger("Mark", "Dhaka")
p5 = Passenger("Jack", "Khulna")
v1.addPassenger(p4, p5)
print("8.===========================")
p4.calculateFare(v1)
print("===========================")
v1.status()
v2 = Vehicle("Chittagong-798", "Car", "Uber", fareChart)
print("9.===========================")
v2.addPassenger(p1)
v2.addPassenger(p3)
print("10.===========================")
p3.calculateFare(v2)
print("11.===========================")
v2.status()
v3 = Vehicle("Khulna-997", "Car", "Obhai", fareChart)
v3.addPassenger(p5)
print("12.===========================")
p5.calculateFare(v3)
print("13.===========================")
v3.status()

1.===========================
Sam has taken the Bus.
2.===========================
Calculating fare for Sam
3.===========================
Destination cannot be empty!
4.===========================
Destination of Bran is updated to Chittagong
5.===========================
John has taken the Bus.
This is an Inter-City Bus. Bran cannot take the Bus.
6.===========================
Calculating fare for John
7.===========================
Mark has taken the Bus.
This is an Inter-City Bus. Jack cannot take the Bus.
8.===========================
Calculating fare for Mark
===========================
Details of Dhaka-123 Bus of SR Travels:
Total Passengers: 3
Passenger name : Sam, Destination: Dhaka, Ticket Price: 40
Passenger name : John, Destination: Dhaka, Ticket Price: 40
Passenger name : Mark, Destination: Dhaka, Ticket Price: 40
9.===========================
This is an Inter-City Car. Sam cannot take the Car.
Bran has taken the Car.
10.===========================
Calculating fare for Bran
11.===========================
Details of Chittagong-798 Car of Uber:
Total Passengers: 1
Passenger name : Bran, Destination: Chittagong, Ticket Price: 250
Jack has taken the Car.
12.===========================
Calculating fare for Jack
13.===========================
Details of Khulna-997 Car of Obhai:
Total Passengers: 1
Passenger name : Jack, Destination: Khulna, Ticket Price: 90

In [5]:
a='dhaka123'
b='hka'
if b in a:
    print(True)

# <font color='darkpink'> Question-8</font>
***Write a Python program that takes multiple words as input from the user and\
calculates the frequency of each word.\
Finally, print all the words (sorted in ascending order) grouped by frequency (sorted in descending order).***\
**<font color="blue">[You can not use built in .count() function]</font>**

**Sample Input #1:**\
cow cat cow ant elephant cow dog lion cat goat cow lion tiger elephant

**Sample Output #2:**\
{\
4 : ['cow'],\
2 : ['cat', 'elephant', 'lion'],\
1 : ['ant', 'dog', 'goat', 'tiger']\
}

**Sample Input #2:**\
cat dog lion cat elephant goat cow lion ant tiger elephant cow cow cow

**Sample Output #2:**\
{\
4 : ['cow'],\
2 : ['cat', 'elephant', 'lion'],\
1 : ['ant', 'dog', 'goat', 'tiger']\
}

In [ ]:
#todo

# <font color='darkpink'> Question-9</font>
***Design the required class(es) so that the following expected output is generated. Do not change any given code.\
Your code should work for any number of arguments in the serverPassenger() method.***

**Output:**\
Bob is waiting for Bus having 800 taka in pocket.\
Simon is waiting for Train having 950 taka in pocket.\
David is waiting for Train having 750 taka in pocket.\
Carol has 1500 taka in pocket.Please buy a ticket.\
1==============================\
This is a general bus and train ticket counter.\
2==============================\
Bob has bought Bus ticket.\
3==============================\
Simon has bought Train ticket.\
4==============================\
David has bought Train ticket.\
Carol please buy a ticket first.\
5==============================\
Carol has bought Train ticket.\
6==============================\
Total passengers:4\
Bus passengers:1\
Passenger Name:Bob Remaining balance:250\
Bus passengers:3\
Passenger Name:Simon Remaining balance:350\
Passenger Name:David Remaining balance:150\
Passenger Name:Carol Remaining balance:900

In [ ]:
# Write you code here



#===============================================
# Do not change the codes below
fareChart = {"Bus":550, "Train":600}
p1 = Passenger("Bob", "Bus Ticket",800)
p2 = Passenger("Simon", "Train Ticket", 950)
p3 = Passenger("David", "Train Ticket", 750)
p4 = Passenger("Carol", 1500)
print("1==============================")
tc = TicketCounter()
print("2==============================")
tc.servePassenger(p1,fareChart)
print("3==============================")
tc.servePassenger(p2,fareChart)
print("4==============================")
tc.servePassenger(p3, p4, fareChart)
print("5==============================")
p4.buyTicket("Train Ticket")
tc.servePassenger(p4,fareChart)
print("6==============================")
tc.showAllPassenger()

# <font color='darkpink'> Question-10</font>
(List,Tuple,Dictionary,String,Function)\
***Suppose, you are working at Bangladesh Road Transportation Authority\
(BRTA). You have to create a report which will show the number of different\
vehicles registered in different cities from the captured images of the\
number plates.***

vehicle_chart = {'KA': 'Private Car', 'KHA': 'Private Car', 'GA': 'Private\
Car', 'GHA':'Jeep', 'CH':'Microbus','CHA':'Laguna','JA':'Minibus','JHA':'Big\
bus','TA':'Big truck','THA':'Pick-up','DO':'Medium\
Truck','NO':'Pick-up','PO':'Taxi-cab','VO':'Private\
Car', 'MO':'Pick-up','DA':'CNG','TH':'CNG', 'HA':'Motorbike','LA':'Motorbike','E':'Truck','ZO':'PM\
Office Vehicles'}

**Input Example:** DHAKA METRO- CHA 67-1234\
Given input will strictly follow this format and must contain a Bangla\
alphabet from the above chart. (here, CHA)

**Task: Now, write a python program which takes the vehicle’s number plate\
data and prints the registered vehicles in the expected output format.\
Here, the first line of input contains the number of vehicle data followed\
by vehicle number plate data which will be provided by the user.**

**Sample Input 1:**\
4\
DHAKA METRO- CHA 12-1289\
DHAKA METRO- KA 67-1281\
DHAKA METRO- KHA 54-1112\
DHAKA METRO- NO 10-1092

**Expected Output 1:**
Registered vehicles:\
{'Laguna': [1, ['12-1289']], 'Private Car': [2, \
['67-1281', '54-1112']], 'Pick-up': [1, ['10-1092']]}

**Output explanation:**
Output will be a dictionary with the number of vehicles in the same\
category and their vehicle number.

**Sample Input 2:**\
5\
CHATTA METRO- CHA 98-1209\
DHAKA METRO- CHA 11-1211\
KHULNA METRO- CHA 13-1098\
CHATTA METRO- KHA 21-1222\
DHAKA METRO- DO 98-1209

**Expected Output 2:**\
Registered vehicles:\
{'Laguna': [3, ['98-1209', '11-1211', '13-1098']], 'Private Car': [1, \
['21-1222']], 'Medium Truck': [1, ['98-1209']]}

In [ ]:
#todo

# <font color='darkpink'> Question-11</font>
***Design the required class(es) so that the following expected output is\
generated. Do not change any given code.***


**Output:**\
1.===========================\
Sam has taken the Bus.\
2.===========================\
Calculating fare for Sam\
3.===========================\
Destination cannot be empty!\
4.===========================\
Destination cannot be empty!\
5.===========================\
Destination of Bran is updated to Kakrail\
6.===========================\
John has taken the Bus.\
7.===========================\
Calculating fare for John\
8.===========================\
Bran has taken the Bus.\
9.===========================\
Calculating fare for Bran\
10.===========================\
Destination cannot be empty!\
11.===========================\
Bus is loaded. Mark cannot take the Bus.\
Bus is loaded. Jack cannot take the Bus.\
12.===========================\
Details of Dhaka-123 Bus:\
Total Passengers: 3\
Passenger name : Sam, Destination: Banani, Fare: 20\
Passenger name : John, Destination: Mohakhali, Fare: 30\
Passenger name : Bran, Destination: Kakrail, Fare: 60\
13.===========================\
Car is loaded. Sam cannot take the Car.\
Car is loaded. Bran cannot take the Car.\
14.===========================\
Details of Chittagong-798 Car:\
Total Passengers: 0

In [ ]:
# Write you code here




#====================================================================
# Do not change the codes below
fareChart = {'Banani': 2, 'Mohakhali':3, 'Mohammadpur':4, 'New 
Market':5, 'Others':6}
v1 = Vehicle("Dhaka-123", "Bus", 3)
p1 = Passenger("Sam", "Banani")
print("1.===========================")
v1.addPassenger(p1)
print("2.===========================")
p1.calculateFare(v1)
print("3.===========================")
p2 = Passenger("John", "Mohakhali")
p3 = Passenger("Bran")
print("4.===========================")
p3.setDestination()
print("5.===========================")
p3.setDestination("Kakrail")
print("6.===========================")
v1.addPassenger(p2)
print("7.===========================")
p2.calculateFare(v1)
print("8.===========================")
v1.addPassenger(p3)
print("9.===========================")
p3.calculateFare(v1)
p4 = Passenger("Mark", "Mohammadpur")
print("10.===========================")
p4.setDestination()
print("11.===========================")
v1.addPassenger(p4)
v1.addPassenger(Passenger("Jack", "New Market"))
print("12.===========================")
v1.details()
v2 = Vehicle("Chittagong-798", "Car", 0)
print("13.===========================")
v2.addPassenger(p1)
v2.addPassenger(p3)
print("14.===========================")
v2.details()

# <font color='darkpink'> Question-12</font>
***Design the required class(es) so that the following expected output is\
generated. Please use the following logic to calculateCost method.\
For each main character the cost is 10000\
For each supporting character the cost is 5000***


**Output:**\
1.============================================\
No characters assigned yet\
2.============================================\
No cost yet as there is no characters\
3.============================================\
Series Name: Sherlock Holmes\
Release Year: 2010\
Language: English\
4.============================================\
5.============================================\
Total Cost: 25000\
6.============================================\
Series Name: Sherlock Holmes\
Release Year: 2010\
Language: English\
Main Characters(s):\
Sherlock Holmes\
James Watson\
Supporting Characters(s):\
Irene Adler\
7.============================================\
[('Sherlock Holmes', 'Main character'), ('James Watson', 'Main character'), \
('Irene Adler', 'Supporting character')]\
8.###############################################\
9.============================================\
No characters assigned yet\
10.============================================\
No cost yet as there is no characters\
11.============================================\
Series Name: Squid Games\
Release Year: 2021\
Language: Korean\
12.============================================\
13.============================================\
Total Cost: 15000\
14.============================================\
Series Name: Squid Games\
Release Year: 2021\
Language: Korean\
Main Characters(s):\
Seong\
Supporting Characters(s):\
Kang\
15.============================================\
[('Seong', 'Main character'), ('Kang', 'Supporting character')]

In [ ]:
# Write you code here




#===================================================================
# You are not allowed to change any given code.
sherlock = Series("Sherlock Holmes", 2010)
print("1.============================================")
print(sherlock.character_list)
print("2.============================================")
sherlock.calculateCost()
print("3.============================================")
sherlock.printDetail()
print("4.============================================")
holmes = Character("Sherlock Holmes", "Main character")
watson = Character("James Watson", "Main character")
irene = Character("Irene Adler")
sherlock.addCharacter(holmes)
sherlock.addCharacter(watson)
sherlock.addCharacter(irene)
print("5.============================================")
sherlock.calculateCost()
print("6.============================================")
sherlock.printDetail()
print("7.============================================")
print(sherlock.character_list)
print("8.###############################################")
squid_games = Series("Squid Games", 2021, "Korean")
print("9.============================================")
print(squid_games.character_list)
print("10.============================================")
squid_games.calculateCost()
print("11.============================================")
squid_games.printDetail()
print("12.============================================")
seong = Character("Seong", "Main character")
kang = Character("Kang")
squid_games.addCharacter(seong)
squid_games.addCharacter(kang)
print("13.============================================")
squid_games.calculateCost()
print("14.============================================")
squid_games.printDetail()
print("15.============================================")
print(squid_games.character_list)